### ISSUE TITLE
Custom schema generation for handling kotlinx.datetime.Instant

### ISSUE THREAD

**Issue by geirsagberg** [bkbnio/kompendium#187]
**Is your feature request related to a problem? Please describe.**
I have the following class:
```kotlin
@Serializable
data class DatasetStatistics(
    val recordCount: Long? = null,
    val lastModified: Instant? = null // kotlinx.datetime.Instant
)
```

When I start the server, I get the following stack trace: 

```
Exception in thread "main" java.lang.IllegalStateException: Unable to parse field type from val kotlinx.datetime.Instant.epochSeconds: kotlin.Long
	at io.bkbn.kompendium.core.Kontent.handleComplexType(Kontent.kt:161)
	at io.bkbn.kompendium.core.Kontent.access$handleComplexType(Kontent.kt:56)
	at io.bkbn.kompendium.core.Kontent$generateKTypeKontent$2.invoke(Kontent.kt:128)
	at io.bkbn.kompendium.core.Kontent$generateKTypeKontent$2.invoke(Kontent.kt:110)
	at io.bkbn.kompendium.core.util.Helpers.logged(Helpers.kt:26)
	at io.bkbn.kompendium.core.Kontent.generateKTypeKontent(Kontent.kt:110)
	at io.bkbn.kompendium.core.Kontent.updateCache(Kontent.kt:232)
	at io.bkbn.kompendium.core.Kontent.handleComplexType(Kontent.kt:172)
	at io.bkbn.kompendium.core.Kontent.access$handleComplexType(Kontent.kt:56)
	at io.bkbn.kompendium.core.Kontent$generateKTypeKontent$2.invoke(Kontent.kt:128)
	at io.bkbn.kompendium.core.Kontent$generateKTypeKontent$2.invoke(Kontent.kt:110)
	at io.bkbn.kompendium.core.util.Helpers.logged(Helpers.kt:26)
	at io.bkbn.kompendium.core.Kontent.generateKTypeKontent(Kontent.kt:110)
	at io.bkbn.kompendium.core.Kontent.generateKontent(Kontent.kt:86)
	at io.bkbn.kompendium.core.KompendiumPreFlight.addToCache(KompendiumPreFlight.kt:47)
```

**Describe the solution you'd like**
I would like for there to be some way I could override the generation of schema for a specific type, e.g. `kotlinx.datetime.Instant`, because I know that it will be serialized as a string.

This seems to have been possible in v1, but is now removed in v2?

In v1 the following works:
```kotlin
    Kompendium.addCustomTypeSchema(
        Instant::class,
        SimpleSchema("string")
    )
```

Could this be re-added, for this type of case where some custom serialization is performed?

Ideally, Kompendium would understand this automatically from the serialization configuration in Ktor, but I imagine that's quite a task 😅 

**Describe alternatives you've considered**
My current workaround is to use `val lastModified: String?` instead, and always do a `.toString()` before creating the object. But it would be nice if Kompendium could be customized to match custom serialization.

**Comment by unredundant** [comment]
You can! Only difference is that it is now part of the declared Kompendium plugin instead of the old global object that used to handle everything :) 

I've made a quick example in #189 

I'm gonna close this, but if you run into any problems feel free to open it back up! 

> Ideally, Kompendium would understand this automatically from the serialization configuration in Ktor, but I imagine that's quite a task 😅

Haha yea, that's not really possible with the current architecture 😄 because even though Kompendium uses the provided serializer to print out the final spec, it still needs to do 
a ton of custom reflection under the hood to build out the schema, which is the point at which this breaks.  

Luckily, it's usually only on weird things like datetime libraries
