### ISSUE TITLE
Date in response body cause NullPointerException

### ISSUE THREAD

**Issue by mvand** [bkbnio/kompendium#325]
**Describe the bug**

When I add a "complex" serialized property, kompendium throws an unexpected error. 
It should happen with other types than `Date`
See steps to reproduce below :

**To Reproduce**

Given : 
```
@Serializable
data class Store(
    @SerialName("id") val id: Int,
    @SerialName("name") val name: String,
)
```

When : 
```
route("/stores/{storeId}") {
      install(NotarizedRoute()) {
            parameters = listOf(
                AuthorizationHeaderParameter,
                StoreIdPathParameter,
            )
            get = GetInfo.builder {
                summary("Get store by storeId")
                description("Full store info")
                response {
                    responseCode(HttpStatusCode.OK)
                    responseType<Store>()
                    description("Store Response")
                }
            }
        }
}
```

Then: OK

**BUT**

Given : 
```
@Serializable
data class Store(
    @SerialName("id") val id: StoreId,
    @SerialName("name") val name: String,
    @Serializable(SimpleDateSerializer::class) @SerialName("date") val date: Date = Date()
)

@Serializer(forClass = Date::class)
class SimpleDateSerializer : KSerializer<Date> {

    companion object {
        const val DATE_FORMAT = "yyyy-MM-dd HH:mm:ss"
    }

    private val df: DateFormat = SimpleDateFormat(DATE_FORMAT)

    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("SimpleDateFormat", PrimitiveKind.STRING)

    override fun deserialize(decoder: Decoder): Date = df.parse(decoder.decodeString())

    override fun serialize(encoder: Encoder, value: Date) {
        encoder.encodeString(df.format(value))
    }
}
```

When: no change for `NotarizedRoute`

Then : Unexpected `NullPointerException`

StackTrace : 
```
Caused by: java.lang.NullPointerException
	at io.bkbn.kompendium.json.schema.handler.SimpleObjectHandler$handle$required$3.invoke(SimpleObjectHandler.kt:56)
	at io.bkbn.kompendium.json.schema.handler.SimpleObjectHandler$handle$required$3.invoke(SimpleObjectHandler.kt:56)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:171)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:787)
	at kotlin.sequences.SequencesKt___SequencesKt.toSet(_Sequences.kt:828)
	at io.bkbn.kompendium.json.schema.handler.SimpleObjectHandler.handle(SimpleObjectHandler.kt:58)
	at io.bkbn.kompendium.json.schema.SchemaGenerator.fromTypeToSchema(SchemaGenerator.kt:58)
	at io.bkbn.kompendium.json.schema.handler.SimpleObjectHandler.handleProperty(SimpleObjectHandler.kt:124)
	at io.bkbn.kompendium.json.schema.handler.SimpleObjectHandler.handle(SimpleObjectHandler.kt:40)
	at io.bkbn.kompendium.json.schema.SchemaGenerator.fromTypeToSchema(SchemaGenerator.kt:58)
	at io.bkbn.kompendium.json.schema.handler.SimpleObjectHandler.handleProperty(SimpleObjectHandler.kt:124)
	at io.bkbn.kompendium.json.schema.handler.SimpleObjectHandler.handle(SimpleObjectHandler.kt:40)
	at io.bkbn.kompendium.json.schema.SchemaGenerator.fromTypeToSchema(SchemaGenerator.kt:58)
	at io.bkbn.kompendium.json.schema.SchemaGenerator.fromTypeOrUnit(SchemaGenerator.kt:72)
	at io.bkbn.kompendium.core.util.Helpers.addToSpec(Helpers.kt:30)
	at io.bkbn.kompendium.core.plugin.NotarizedRoute$invoke$2.invoke(NotarizedRoute.kt:71)
	at io.bkbn.kompendium.core.plugin.NotarizedRoute$invoke$2.invoke(NotarizedRoute.kt:43)
	at io.ktor.server.application.CreatePluginUtilsKt.setupPlugin(CreatePluginUtils.kt:175)
	at io.ktor.server.application.CreatePluginUtilsKt.createPluginInstance(CreatePluginUtils.kt:168)
	at io.ktor.server.application.CreatePluginUtilsKt.access$createPluginInstance(CreatePluginUtils.kt:1)
	at io.ktor.server.application.CreatePluginUtilsKt$createRouteScopedPlugin$1.install(CreatePluginUtils.kt:93)
	at io.ktor.server.application.CreatePluginUtilsKt$createRouteScopedPlugin$1.install(CreatePluginUtils.kt:79)
	at io.ktor.server.application.ApplicationPluginKt.installIntoRoute(ApplicationPlugin.kt:142)
	at io.ktor.server.application.ApplicationPluginKt.install(ApplicationPlugin.kt:91)
```

**Expected behavior**
No error.

**Additional context**
Happen on `v3.3.0`

**Comment by unredundant** [comment]
Did you happen to define a custom type?  You will need to do that for anything that could be considered a "complex scalar" (pretty much anything that represents a date or timestamp would fall in this category) 

https://github.com/bkbnio/kompendium/blob/main/playground/src/main/kotlin/io/bkbn/kompendium/playground/CustomTypePlayground.kt#L49-L51

**Comment by mvand** [comment]
You were right. I was missing a custom TypeDefinition. 

The NullPointerException didn't give me a clue about the existence of this requirement, then I thought it was not supported yet.

Thanks for your help 👌

**Comment by unredundant** [comment]
Glad you got it fixed, definitely agree that we should make that error message more instructive

**Comment by unredundant** [comment]
Added more instructive stack trace in #327
