### ISSUE TITLE
Serialization fails for response example

### ISSUE THREAD

**Issue by serpro69** [bkbnio/kompendium#380]
Here's a minimal reproducible example using the `BasicPlayground` : https://github.com/serpro69/kompendium/tree/serialization_failure 

- run main of `Basic Playground`
- open docs at `localhost:8081/docs`
- see the error thrown

Looks like an issue with `AnySerializer` :

```
kotlinx.serialization.SerializationException: Serializer for class 'Response' is not found.
Mark the class as @Serializable or provide the serializer explicitly.
	at kotlinx.serialization.internal.Platform_commonKt.serializerNotRegistered(Platform.common.kt:91)
	at kotlinx.serialization.SerializersKt__SerializersKt.serializer(Serializers.kt:149)
	at kotlinx.serialization.SerializersKt.serializer(Unknown Source)
	at io.bkbn.kompendium.oas.serialization.AnySerializer.serialize(AnySerializer.kt:26)
	at io.bkbn.kompendium.oas.serialization.AnySerializer.serialize(AnySerializer.kt:15)
```

**Comment by unredundant** [comment]
also could you push this branch to the upstream?

**Comment by serpro69** [comment]
I don't have permissions to push a branch to this repo, so you'll have to pull it yourself. Or I can make a PR that you can later pull and close? 
And also do you want it in the state it is ? It was just a dirty example to reproduce the error, nothing more :)

**Comment by unredundant** [comment]
oh really you can't push upstream? I thought that restriction was just on master 🤔 Don't worry about it then

**Comment by unredundant** [comment]
This is fixed in v4
